services:
  postgres:
    image: postgres:16
    container_name: pg-podcast-index-manger
    environment:
      POSTGRES_DB: "podcast-index-manger"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin123"
    ports:
      - "5432:5432"
    volumes:
      - podcast_index_manger_pg:/var/lib/postgresql/data

volumes:
  podcast_index_manger_pg:
